export enum ActivityEventType {
  USER_LOGIN = 'USER_LOGIN',
  USER_REGISTERED = 'USER_REGISTERED',
  CASE_CREATED = 'CASE_CREATED',
  CASE_ASSIGNED = 'CASE_ASSIGNED',
  CASE_STATUS_UPDATED = 'CASE_STATUS_UPDATED',
}

export enum EntityType {
  USER = 'USER',
  CASE = 'CASE',
  ASSIGNMENT = 'ASSIGNMENT',
}
